#!/usr/bin/env python
#
# Example: ./lsd-import-twomass -c -f twomass_list twomass /home/ptfbs/projects/DB/2MASS_orig/ >output_twomass 2>errors_twomass
#

import sys
import getopt
from lsd import DB
import lsd.two_mass as twomass
from lsd.utils import *
from lsd.tui import *
import numpy as np
import shutil
import subprocess

def usage():
	print "Usage: %s [-c|--create] <twomass_table> <sweep_file_dir>" % sys.argv[0]

optlist, (dbdir,), (tabname, sweep_dir) = tui_getopt('cf:', ['create', 'file=',], 2, usage)

create = False
filelist = 'None'
for (o, a) in optlist:
	if o == '-c' or o == '--create':
		create = True
	if o == '-f' or o == '--file':
		filelist = str(a)

if create:
	if os.access(dbdir+'/'+tabname, os.F_OK):
		subprocess.check_call(['chmod', '-R', '755', dbdir+'/'+tabname])
		shutil.rmtree(dbdir+'/'+tabname)

#
# Actual work
#
db = DB(dbdir)

if filelist != 'None':
	files = np.genfromtxt(filelist, dtype='a')
else:
	files = shell('find "' + sweep_dir + '" -name "strip.*"').splitlines()

with db.transaction():

	print "Importing SDSS catalog:"
	twomass.import_from_sweeps(db, tabname, files, create)
	print " done."
